### ISSUE TITLE
AHP in heating & A/C?

### ISSUE THREAD

**Issue by bbartling** [ani-rudra-chan/AHP-Python-Project#1]
Hi Anirudh,

Could you ever give me a tip if I could incorporate AHP into my process with heating and A/C system application? Great medium.com article btw :)

So I am just making up data here imagine a large commercial office building with an AC system running in the summer time.

So there is two columns in a pandas dataframe one named `Air_Flow`  and other named `Stp_Deviation` that stands for setpoint deviation. In an office building individual zone this is just a calculated value for the zone temperature - zone temperature setpoint. Easy way to tell if a zone isnt meeting setpoint on a building automation system.

```
import random
import numpy as np
import pandas as pd

data = np.random.randint(0,2000,size=15)
df = pd.DataFrame(data, columns=['Air_Flow'])


#generate random floats for df2
randomFloatList = []
# Set a length of the list to length of pandas df1
for i in range(0, len(df)):
    # any random float between 5.50 to 50.50
    x = round(random.uniform(-3.50, 5.50), 2)
    randomFloatList.append(x)

#setpointDeviation = ZoneTemp - ZoneSetpoint
df2 = pd.DataFrame(randomFloatList,columns=['Stp_Deviation'])


df3 = df.join(df2)
#print(df3)
#print(df3.sort_values(['Air_Flow','Stp_Deviation'], ascending=[False, False]))

df3['weighted'] = df3['Air_Flow'] * df3['Stp_Deviation']
print(df3)

ranked = df3.sort_values(['weighted'], ascending=[True])
print(ranked)
```

printing df3 looks like this below. Air flow would be in volume of air (CFM) and setpoint deviation is temperature in degrees F. If this was real live data its an easy way for me to see large zones (flows over 1000 CFM) and zones that are too hot, at setpoint, or under setpoint.

```
    Air_Flow  Stp_Deviation  weighted
0       1511          -0.48   -725.28
1        436           2.33   1015.88
2       1433          -1.86  -2665.38
3        238          -0.20    -47.60
4        658           2.81   1848.98
5       1445           5.05   7297.25
6       1938           4.98   9651.24
7        305           0.63    192.15
8       1247          -0.44   -548.68
9        910          -0.17   -154.70
10       801           3.26   2611.26
11       782           2.54   1986.28
12      1994          -0.41   -817.54
13      1248           5.25   6552.00
14       172           3.58    615.76
```

The `weighted` column is just something I made up scratching my head trying to sort a list based on criteria:

- Select top 5 zones that are at or under setpoint (most important)
- Select top 5 largest zones by highest air flow (second importance)

In an ideal situation I would want to select zones that are large and not over zone temperature setpoint to shut down in first in order to control the building power consumption from the A/C system running. The larger the zone the more power/electricity it would consume. Hopefully that makes sense...

Could I ever design this into an AHP problem to rank? Any comment on the weighted column for something I made up greatly appreciated. Not alot of experience in computer science algorithms, data science, or this sort of thinking :)

**Comment by ani-rudra-chan** [comment]
Hi Ben,

I have uploaded a notebook on the problem you have stated above. Please have a look and let me know your thoughts. You can perhaps resolve this issue without resorting to AHP and instead use a simple scoring method.

**Comment by bbartling** [comment]
Anirudh thank you so much for this ...
